require 'rack/oauth2'

class FacebooksController < ApplicationController
  #before_filter :require_authentication, :only => :destroy

  rescue_from Rack::OAuth2::Client::Error, :with => :oauth2_error
  
  def index
    
  end

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    auth = Facebook.auth(root_url).from_cookie(cookies)
    logger.info auth.data.inspect
    auth.authorized!
    authenticate Facebook.identify(auth.user)
    redirect_to dashboard_url
  end

  def profile
    @fb_user = Facebook.find_by_user_id(current_user.id)
    @user = FbGraph::User.me(@fb_user.access_token).fetch
    @album = @user.albums   
  end
  
  def wall
    @fb_user = Facebook.find_by_user_id(current_user.id)
    @user = FbGraph::User.me(@fb_user.access_token).fetch
      
  end
  # handle Normal OAuth flow: start
  def new
    redirect_to client.authorization_uri(
      :scope => Facebook.config[:scope]
    )
  end

  # handle Normal OAuth flow: callback
  def facebook_create
    client.authorization_code = params[:code]
    access_token = client.access_token!
    @user = FbGraph::User.me(access_token).fetch
    Facebook.identify(@user, current_user.id)
    @user = User.find(current_user.id)
    @user.update_attributes(:facebook_confirmation => 1)
    redirect_to wall_facebooks_url
  end

  def destroy
    unauthenticate
    redirect_to root_url
  end
  
  def timeline
    @fb_user = Facebook.find_by_user_id(current_user.id)
    @user = FbGraph::User.me(@fb_user.access_token).fetch
    @posts = @user.home
    @friends = @user.friends
  end
  
  def friends_list
    @fb_user = Facebook.find_by_user_id(current_user.id)
    @user = FbGraph::User.me(@fb_user.access_token).fetch
    @friends = @user.friends
  end

  def update_status
    @fb_user = Facebook.find_by_user_id(current_user.id)
    @user = FbGraph::User.me(@fb_user.access_token).fetch
    @user.feed!(
      :message => params[:message]
    )
    redirect_to wall_facebooks_path
  end

  private

  def client
    unless @client
      @client = Facebook.auth.client
      @client.redirect_uri = facebook_create_facebooks_url
    end
    @client
  end

  def oauth2_error(e)
    flash[:error] = {
      :title => e.response[:error][:type],
      :message => e.response[:error][:message]
    }
    redirect_to root_url
  end
  
  
end
